apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: darkside
  name: darkside
spec:
  containers:
  - image: nginx
    name: darkside
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
