apiVersion: v1
kind: Pod
metadata:
  name: strix-dual-webserver
  labels:
    app: dual-webserver
spec:
  containers:
    - name: nginx-webserver
      image: nginx:latest
      ports:
        - containerPort: 80
          name: http-nginx
      volumeMounts:
        - mountPath: /strixdir
          name: first-emptydir
      resources:
        limits:
          cpu: "1.3"
          memory: "150Mi"
        requests:
          cpu: "0.8"
          memory: "75Mi"

    - name: apache-webserver
      image: httpd:latest
      ports:
        - containerPort: 8080
          name: http-apache
      volumeMounts:
        - mountPath: /strixdir/apache
          name: first-emptydir
      resources:
        limits:
          cpu: "0.7"
          memory: "100Mi"
        requests:
          cpu: "0.4"
          memory: "50Mi"

  dnsPolicy: ClusterFirst
  restartPolicy: Always
  
  volumes:
    - name: first-emptydir
      emptyDir:
        sizeLimit: 256Mi
