apiVersion: v1
kind: Pod
metadata:
  name: giropops
  labels:
    run: giropops
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      args:
        - sleep
        - "1800"
      resources:
        limits:
          cpu: "1.5"
          memory: "128Mi"
        requests:
          cpu: "0.3"
          memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
